name: CI/CD FESTIVA

permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8 black pylint

      - name: Check formatting with Black
        run: black app/

      - name: Run tests
        run: |
          export PYTHONPATH=$PWD
          pytest
       
      # Alerta quando falha
      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Falha de testes no Projeto FESTIVA"
          from: github-actions@festiva.com
          to: ${{ secrets.EMAIL_USERNAME }}
          body: "Os testes falharam. Verifique a PR."

      # Alerta quando sucesso
      - name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Sucesso nos testes do Projeto FESTIVA"
          from: github-actions@festiva.com
          to: ${{ secrets.EMAIL_USERNAME }}
          body: "Todos os testes passaram com sucesso!"    

           

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: festivaZIP
          path: |
            **/*.py
            README.md

  cd:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci   # só roda se CI passar
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: festivaZIP

      - name: Simulate deploy
        run: |
          echo "✅ Artifact downloaded successfully"
          echo "✅ Deploy simulated: FESTIVA would be deployed here"
          ls -R  # mostra os arquivos baixados 
  
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: ci   # só roda se o CI passar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/festiva-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/festiva-app:latest        