name: CI/CD Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Login no Docker Hub
      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build da imagem Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/festiva:latest .

      # 4. Testar o container localmente (deploy simulado)
      - name: Run container
        run: |
          docker run -d -p 8000:8000 --name festiva-test ${{ secrets.DOCKER_USERNAME }}/festiva:latest
          sleep 5  # espera subir
          curl -f http://localhost:8000/ || (docker logs festiva-test && exit 1)

      # 5. Push para Docker Hub (só se o teste passar)
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/festiva:latest
